{{- range $modelSpec := .Values.servingEngineSpec.modelSpec }}
{{- with $ -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-{{$modelSpec.name}}-storage-claim"
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    {{- if $modelSpec.pvcAccessMode }}
    {{- toYaml $modelSpec.pvcAccessMode | nindent 4 }}
    {{- else }}
    - ReadWriteOnce
    {{- end }}
  resources:
    requests:
      storage: {{ $modelSpec.pvcStorage | default "20Gi" }}  # Default to 40Gi if not set
  {{- if $modelSpec.storageClass }}
    {{- if eq $modelSpec.storageClass "efs_static_storage_class_indicator" }}
  storageClassName: ""
    {{- else }}
  storageClassName: "{{ $modelSpec.storageClass }}"
    {{- end }}
  {{- end }}
  {{- if not (empty $modelSpec.pvcMatchLabels) }}
  selector:
    matchLabels:
      {{- toYaml $modelSpec.pvcMatchLabels | nindent 8 }}
  {{- end }}
{{- end }}
---
{{- end }}
