{{- range $modelSpec := .Values.servingEngineSpec.modelSpec }}
{{- with $ -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-{{$modelSpec.name}}-storage-claim"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
{{- if $modelSpec.pvcAnnotations }}
    {{- toYaml $modelSpec.pvcAnnotations | nindent 4 }}
{{- end }}
spec:
  accessModes:
    {{- if $modelSpec.pvcAccessMode }}
    {{- toYaml $modelSpec.pvcAccessMode | nindent 4 }}
    {{- else }}
    - ReadWriteOnce  # Default to EBS-compatible mode if not specified
    {{- end }}
  resources:
    requests:
      storage: {{ $modelSpec.pvcStorage | default "10Gi" }}  # Default to 10Gi if not set
  {{- if $modelSpec.storageClass }}
  storageClassName: "{{ $modelSpec.storageClass }}"  # Allow user-defined storageClass
  {{- end }}
  {{- if not (empty $modelSpec.pvcMatchLabels) }}
  selector:
    matchLabels:
      {{- toYaml $modelSpec.pvcMatchLabels | nindent 8 }}
  {{- end }}
{{- end }}
---
{{- end }}