apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secrets"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $modelSpec := .Values.servingEngineSpec.modelSpec }}
  {{- with $ -}}
  {{-   if $modelSpec.hf_token }}
  hf_token_{{ $modelSpec.name }}: {{ $modelSpec.hf_token | b64enc | quote }}
  {{-   end }}
  {{- end }}
  {{- end }}
